### ISSUE TITLE
How to add captions/subtitle tracks?

### ISSUE THREAD

**Issue by Footprint-Addons** [brightcove/videojs-playlist-ui#104]
## Description
Hi there,
Wonderful plugin! I've set up a playlist without problems, but I don't know whether it is possible to add subtitle/captions tracks. I tried to place a track block with multiple language files in the same way as with regular videojs videos, but they don't show up, nor is there a CC button to activate them.
I tried to place the track block in every conceivable location (first video in playlist) but no luck. 
Any idea how to solve this?

Test page:
https://enterprise.wp21century.com/videojs/hls-playlist.html
On the first video I tried to attach captions.

## Steps to reproduce
See source code test page.

### Expected
To show a CC button, like in single videos.

### Error output
Only CORS header errors with the thumbnail images because I moved the html page to another domain but this has no bearing with the tracks issue. You can safely disregard that.

### versions
videojs-playlist-ui 3.5.2

### videojs
Version 7.5.0 and 7.5.2

#### browsers
Latest Chrome, IE, Firefox, Safari

#### OSes
Linux

Thank you beforehand! :-)

**Comment by gkatsev** [comment]
The property name is `textTracks` and not just tracks. See https://github.com/brightcove/videojs-playlist/blob/master/docs/api.md#playlist-item-object

Hope this helps.

**Comment by Footprint-Addons** [comment]
Hi @gkatsev,
Yes, that did the trick. Thank you so much for your fast and accurate response! :-)

**Comment by gkatsev** [comment]
You're welcome!
