### ISSUE TITLE
Custom url playlist-item

### ISSUE THREAD

**Issue by netwebvn** [brightcove/videojs-playlist-ui#134]
hello i have 1 url like this
https://videojs.com/advanced/?video=bipbop-advanced

How can I customize the url on a playlist like that for each video, when the user copies exactly each url to each video in the playlist

![url](https://user-images.githubusercontent.com/32257723/115816508-2797c300-a423-11eb-9ddc-1d971beb175a.jpg)

**Comment by gkatsev** [comment]
Here's the videojs.com/advanced implementation:
https://github.com/videojs/videojs.com/blob/379f9b0a2b463c6d56cde5eb3861f5d3754be88a/src/components/HomeComponents/AdvancedExample/index.jsx#L128-L131
https://github.com/videojs/videojs.com/blob/379f9b0a2b463c6d56cde5eb3861f5d3754be88a/src/components/HomeComponents/AdvancedExample/index.jsx#L106-L115

Hope this helps!

**Comment by netwebvn** [comment]
Thank you for your help!
