### ISSUE TITLE
css does not get applied when using a custom className

### ISSUE THREAD

**Issue by forbesjo** [brightcove/videojs-playlist-ui#15]
When using the className argument ( `player.playlistUi({ className: 'vjs-playlist2' })` ) the class `vjs-playlist` is not added to the `ol`.

**Comment by forbesjo** [comment]
A way to work around this would be to include `vjs-playlist` and `vjs-playlist2` classes in the ol. If this is as designed the documentation should be updated.

**Comment by gkatsev** [comment]
Yep, that's what I meant. You should include `vjs-playlist` and then whatever other means of selecting a specific item.

**Comment by gkatsev** [comment]
Going to close this one. Class of `vjs-playlist` should be required regardless of what other classes the user adds.
