### ISSUE TITLE
Hmm dist folder on this one?

### ISSUE THREAD

**Issue by fmp777** [brightcove/videojs-playlist-ui#19]
Looking for dist folder for css and js.  Checked the different tags and master.  The example references a dist folder that doesn't exist.

**Comment by fmp777** [comment]
PS: I already have what I need (compiled the less and fixed the JS) but you might want to add the dist folder back in?

**Comment by gkatsev** [comment]
We published to npm and the dist is generated for it. We haven't been committing it into the repo. We'll consider building it and getting it published to the github releases.
