### ISSUE TITLE
Auto play next video after the video ended.

### ISSUE THREAD

**Issue by RathanakSreang** [brightcove/videojs-playlist-ui#20]
Currently I try to make my playlist automatically play the next video. So do we have callback for this problem ?

**Comment by gkatsev** [comment]
If you're using [videojs-playlist](https://github.com/brightcove/videojs-playlist/), it has a method for that: https://github.com/brightcove/videojs-playlist/blob/master/docs/api.md#playerplaylistautoadvancenumber-delay---undefined
