### ISSUE TITLE
Can I create  tow  playlist-UI windows?

### ISSUE THREAD

**Issue by victor72** [brightcove/videojs-playlist-ui#22]
with the playlist-ui,  I can do the things as " the advanced live example" easily.

But I wonder how can I clear and initial the "vjs-playlist" OL ? 
 the things just as : 
now I have 2 playlist var player1 & player2

if the function can bring some parameters? such as :   player2.playlistUi("vjs-playlist") ?

**Comment by misteroneill** [comment]
The README has information on using multiple playlists on a single page. This behavior was further improved in v3.1.0.
