### ISSUE TITLE
 Video.js 5.11.7 

### ISSUE THREAD

**Issue by pipechaves** [brightcove/videojs-playlist-ui#25]
Not sure if its the version of the videoJS

but with the latest realease of playlist-ui  (Sep 8 v3.0.0 ) when you add the script videojs-playlist-ui.js there is an error  "videojs-playlist-ui.js:5 Uncaught SyntaxError: Unexpected token import" 

Line 5 shows --     import videojs from 'video.js';

How I add the videojs-playlist-ui was

<script src="video.js"></script>

<script src="videojs-playlist.js"></script>

<script src="videojs-playlist-ui.js"></script>

if I remove the <script src="videojs-playlist-ui.js"></script>  the error is gone.

Regards

**Comment by gkatsev** [comment]
You can't use the file directly. You need to use the released version on npm or the standalone file that's available on npm: https://unpkg.com/videojs-playlist-ui@3.0.0/dist/videojs-playlist-ui.js

We probably should upload that file to github but npm is where we publish releases.
