### ISSUE TITLE
Multiple instances on page

### ISSUE THREAD

**Issue by diniscorreia** [brightcove/videojs-playlist-ui#28]
Hi there,

Is it possible to support multiple instances on a single page? 

I have two different players and I'm initializing the plugin on two different elements with specific class names. However, all the items get added to the same element.

It does work - if I click an item on the UI it starts plugin on its player - but the items should be on different elements.

**Comment by gkatsev** [comment]
You can do it, we should see if we can try to do it automatically, but in the meantime, you just need to pass in [a `className` option](https://github.com/brightcove/videojs-playlist-ui#classname) to each instantiation of the playlist-ui to disambiguate which container you want to use.

**Comment by diniscorreia** [comment]
@gkatsev that's what I'm doing - like I said, the items do play on the correct player, but they all get appended to the same element, even with a different className.

I think I found the bug and will submit a pull request (seems like when creating the element it looks for `vjs-playlist-item-list` on the whole document and not just the playlist UI element).

**Comment by SStembridge** [comment]
I'm having this issue right now. I have a couple instances of playlists on the same page. The list elements are created but are both appended to the first playlist even though I pass different classNames to both of them.
Something like this:
before playlistUi:
```
<video id='1'>...</video>
<div class="video-1"></div>
<video id='2'>...</video>
<div class="video-2"></div>
```
playlistUi calls:
```
var player1 = videojs($('#1'));
player1.playlist(...);
player1.playlistUi({className:'video-1'});
var player2 = videojs($('#2));
player2.playlist(...);
player1.playlistUi({className:'video-2'});
```
after playlistUi calls:
```
<video id='1'>...</video>
<div class="video-1 vjs-csspointerevents vjs-mouse">
  <ol class="vjs-playlist-item-list">
    <li class="vjs-playlist-item">playlist 1 item</li>
    <!--... (more playlist 1 items)-->
    <li class="vjs-playlist-ad-overlay"></li>
    <li class="vjs-playlist-item">playlist 2 item</li>
    <!--... (more playlist 2 items)-->
    <li class="vjs-playlist-ad-overlay"></li>
  </ol>
</div>
<video id='2'>...</video>
<div class="video-2 vjs-csspointerevents vjs-mouse"></div>
```

The different players will still play the right videos, the items are just all put in the same element, like diniscorreia says.

**Comment by misteroneill** [comment]
We introduced a change in 3.1.0 (in #51) that makes support for this use-case a bit better. The plugin will now, by default, look for the first - _unused_ - `.vjs-playlist` container element.

I think we'd like to have a better API for this, but we were reluctant to do anything that could be considered a breaking change.
