### ISSUE TITLE
dist/ in npmignore is breaking the build branch

### ISSUE THREAD

**Issue by gkatsev** [brightcove/videojs-playlist-ui#3]

**Comment by dmlap** [comment]
![](https://s-media-cache-ak0.pinimg.com/236x/5c/b8/4f/5cb84f4b6036ede6bd3a453a97fdb279.jpg)

**Comment by forbesjo** [comment]
Closed by https://github.com/brightcove/videojs-playlist-ui/commit/2beef28b438032dbafacdbc5d33d0872470da964
:cow2:
