### ISSUE TITLE
How to download latest release without any import statements?

### ISSUE THREAD

**Issue by oshihirii** [brightcove/videojs-playlist-ui#36]
Re:

https://github.com/brightcove/videojs-playlist-ui/releases/tag/v3.0.3

I want to upgrade to this version, however the file in the above zip contains import statements, eg:

    import videojs from 'video.js'; 

I believe that in order to generate a usable file you have to use grunt and "build things"? (See:  https://github.com/brightcove/videojs-playlist-ui/issues/25#issuecomment-254371725)

Can I access a usable version of this file without having to do this "build process".

Thank You.

**Comment by oshihirii** [comment]
I tried this url:

https://unpkg.com/videojs-playlist-ui@3.0.3/dist/videojs-playlist-ui.js

But got:

    Not found: package videojs-playlist-ui@3.0.3

**Comment by misteroneill** [comment]
@oshihirii Sorry about that - we pushed the tag up, but neglected to publish it to npm. It's available on unpkg.com now!
