### ISSUE TITLE
Reinitializing the plugin does not remove the original playlist

### ISSUE THREAD

**Issue by forbesjo** [brightcove/videojs-playlist-ui#9]
Executing `player.playlistUi()` more than once does not remove the previous playlist items.

![screen shot 2015-08-06 at 1 30 22 pm](https://cloud.githubusercontent.com/assets/7529098/9118575/4fac6f5a-3c3f-11e5-96ed-bf43b4de1e82.png)

**Comment by AlexLi88** [comment]
I got the same problem
